server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Main definition linked to /usr/share/nginx/html
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # Enable JSON autoindex for recordings
    location /recordings/ {
        autoindex on;
        autoindex_format json;
        add_header Access-Control-Allow-Origin *;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
